const REDIRECT_URI = import.meta.env.VITE_REDIRECT_URI;
const LOGOUT_REDIRECT_URI = import.meta.env.VITE_LOGOUT_REDIRECT_URI;
const KAKAO_TOKEN_CODE_URL = import.meta.env.VITE_KAKAO_TOKEN_CODE_URL;
const KAKAO_AUTH_CODE_URL = import.meta.env.VITE_KAKAO_AUTH_CODE_URL;
const KAKAO_TOKEN_LOGOUT_URL = import.meta.env.VITE_KAKAO_TOKEN_LOGOUT_URL;
const KAKAO_RENEW_TOKEN_URL = import.meta.env.VITE_KAKAO_RENEW_TOKEN_URL;
const KAKAO_USERINFO_URL = import.meta.env.VITE_KAKAO_USERINFO_URL;
const KAKAO_ACCOUNT_LOGOUT_URL = import.meta.env.VITE_KAKAO_ACCOUNT_LOGOUT_URL;

export {
  REDIRECT_URI,
  LOGOUT_REDIRECT_URI,
  KAKAO_TOKEN_CODE_URL,
  KAKAO_AUTH_CODE_URL,
  KAKAO_TOKEN_LOGOUT_URL,
  KAKAO_RENEW_TOKEN_URL,
  KAKAO_USERINFO_URL,
  KAKAO_ACCOUNT_LOGOUT_URL,
};
