
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    active: server   # 로컬 프로파일 사용을 위한 설정
  jpa:
    hibernate:
      ddl-auto: create
      profiles:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
  data:
    web:
      pageable:
        one-indexed-parameters: true
jwt:
  key:
    secret: ${JWT_SECRET}
    admin:
      list: admin@gmail.com,admin1@gmail.com,admin2@gmail.com,admin3@gmail.com

cos:
  key: ${COS_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 1440

mail:
  address:
